@pizza-store = localhost:8001

### Place a new order
# @name postRequest
POST http://{{pizza-store}}/orders 
content-type: application/json

{ "customer": { "name": "fernando", "email": "fernando@email.com" }, "items": [ { "type":"vegetarian", "amount": 2 } ], "address": "KubeCon Salt Lake City", "creditCard": "1111-22222-3333-44444", "drink": "Soda", "event": "Sent to kitchen" }

###Get order
@order-id = {{postRequest.response.body.order_id}}
GET http://{{pizza-store}}/orders/{{order-id}}

###Delete order
DELETE http://{{pizza-store}}/orders/{{order-id}}