### Place orders
@pizza-store = localhost:8001

### Place a new order
POST http://{{pizza-store}}/orders 
content-type: application/json

{ "customer": { "name": "fernando", "email": "fernando@email.com" }, "items": [ { "type":"vegetarian", "amount": 2 } ], "address": "KubeCon Salt Lake City", "creditCard": "1111-22222-3333-44444", "drink": "Soda", "event": "Sent to kitchen" }

###Get order
GET http://{{pizza-store}}/orders/6f0f138e-2883-466c-b6c1-ef4ce67f4a41
content-type: application/json

###Delete order
DELETE http://{{pizza-store}}/orders/6f0f138e-2883-466c-b6c1-ef4ce67f4a41
content-type: application/json